
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'ABB3_pcie_4_lane_Emu_FIFO_elink.ucf'
####################################################################################

##-----------------------------------------------------------------------------
##
## (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.
##
##-----------------------------------------------------------------------------
## Project    : Series-7 Integrated Block for PCI Express
## File       : xilinx_pcie_2_1_ep_7x_04_lane_gen2_xc7a200t-fbg676-2_AC701.ucf
## Version    : 1.11

###############################################################################
# Define Device, Package And Speed Grade
###############################################################################


#########################################################################################################################
# User Constraints
#########################################################################################################################

###############################################################################
# User Time Names / User Time Groups / Time Specs
###############################################################################

###############################################################################
# User Physical Constraints
###############################################################################

#########################################################################################################################
# End User Constraints
#########################################################################################################################
#
#
#
#########################################################################################################################
# PCIE Core Constraints
#########################################################################################################################

###############################################################################
# Pinout and Related I/O Constraints
###############################################################################

#
# SYS reset (input) signal.  The sys_reset_n signal should be
# obtained from the PCI Express interface if possible.  For
# slot based form factors, a system reset signal is usually
# present on the connector.  For cable based form factors, a
# system reset signal may not be available.  In this case, the
# system reset signal must be generated locally by some form of
# supervisory circuit.  You may change the IOSTANDARD and LOC
# to suit your requirements and VCCO voltage banking rules.
# Some 7 series devices do not have 3.3 V I/Os available.
# Therefore the appropriate level shift is required to operate
# with these devices that contain only 1.8 V banks.
#


# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:100
set_false_path -through [get_nets sys_reset_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:101
# The constraint 'NODELAY' is not supported in this version of software. It will not be converted.
#
#NET "sys_reset_n" NODELAY = "TRUE";

set_property PACKAGE_PIN M20 [get_ports sys_reset_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sys_reset_n' has been applied to the port object 'sys_reset_n'.
set_property IOSTANDARD LVCMOS33 [get_ports sys_reset_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:104
# The conversion of 'PULL' constraint on 'net' object 'sys_reset_n' has been applied to the port object 'sys_reset_n'.
set_property PULLUP true [get_ports sys_reset_n]

#
# LED Status Indicators for Example Design.
# LED 0-2 should be ON if link is up and functioning correctly
# LED 3 should be blinking if user applicaiton is receiving valid clock
#
#NET  "led_0"              LOC = M26     | IOSTANDARD = LVCMOS33;  # System Reset
#NET  "led_1"              LOC = T24     | IOSTANDARD = LVCMOS33;  # User Reset
#NET  "led_2"              LOC = T25     | IOSTANDARD = LVCMOS33;  # User Link Up
#NET  "led_3"              LOC = R26     | IOSTANDARD = LVCMOS33;  # User Clk Heartbeat
#
# SYS clock 100 MHz (input) signal. The sys_clk_p and sys_clk_n
# signals are the PCI Express reference clock. Virtex-7 GT
# Transceiver architecture requires the use of a dedicated clock
# resources (FPGA input pins) associated with each GT Transceiver.
# To use these pins an IBUFDS primitive (refclk_ibuf) is
# instantiated in user's design.
# Please refer to the Virtex-7 GT Transceiver User Guide
# (UG) for guidelines regarding clock resource selection.
#
set_property PACKAGE_PIN F11 [get_ports sys_clk_p]
set_property PACKAGE_PIN E11 [get_ports sys_clk_n]

#
# Transceiver instance placement.  This constraint selects the
# transceivers to be used, which also dictates the pinout for the
# transmit and receive differential pairs.  Please refer to the
# Virtex-7 GT Transceiver User Guide (UG) for more information.
#

# PCIe Lane 0
set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN C10 [get_ports {pci_exp_txn[0]}]
set_property PACKAGE_PIN C12 [get_ports {pci_exp_rxn[0]}]
set_property PACKAGE_PIN D12 [get_ports {pci_exp_rxp[0]}]
set_property PACKAGE_PIN D10 [get_ports {pci_exp_txp[0]}]
# PCIe Lane 1
set_property LOC GTPE2_CHANNEL_X0Y6 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN A9 [get_ports {pci_exp_txn[1]}]
set_property PACKAGE_PIN A13 [get_ports {pci_exp_rxn[1]}]
set_property PACKAGE_PIN B13 [get_ports {pci_exp_rxp[1]}]
set_property PACKAGE_PIN B9 [get_ports {pci_exp_txp[1]}]
# PCIe Lane 2
set_property LOC GTPE2_CHANNEL_X0Y5 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN C8 [get_ports {pci_exp_txn[2]}]
set_property PACKAGE_PIN C14 [get_ports {pci_exp_rxn[2]}]
set_property PACKAGE_PIN D14 [get_ports {pci_exp_rxp[2]}]
set_property PACKAGE_PIN D8 [get_ports {pci_exp_txp[2]}]
# PCIe Lane 3
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN A7 [get_ports {pci_exp_txn[3]}]
set_property PACKAGE_PIN A11 [get_ports {pci_exp_rxn[3]}]
set_property PACKAGE_PIN B11 [get_ports {pci_exp_rxp[3]}]
set_property PACKAGE_PIN B7 [get_ports {pci_exp_txp[3]}]

# GTP Common Placement
set_property LOC GTPE2_COMMON_X0Y1 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[0].pipe_quad.pipe_common.qpll_wrapper_i/gtp_common.gtpe2_common_i}]

#
# PCI Express Block placement. This constraint selects the PCI Express
# Block to be used.
#

set_property LOC PCIE_X0Y0 [get_cells pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i]

#
# BlockRAM placement
#
set_property LOC RAMB36_X2Y46 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y47 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y46 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y45 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y44 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y43 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y42 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]
set_property LOC RAMB36_X1Y41 [get_cells {pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/ramb_bl.ramb36_dp_bl.ram36_bl}]

# Lock down the FIFO
#INST "v7_pcie_i/FPC_top_i/pr_loader_i/PIO_FPC_i/PIO_EP_FPC_inst/data_transfer_i/fastConfigFIFO_i/U0/xst_fifo_generator/gconvfifo.rf/gbiv5.bi/v6_fifo.fblk/gextw[1].gnll_fifo.inst_extd/gonep.inst_prim/gf18e1_inst.sngfifo18e1" LOC = RAMB18_X4Y74 ;


###############################################################################
# Timing Constraints
###############################################################################

#NET "v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_250mhz" TNM_NET = "CLK_250";
#NET "v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_250mhz" TIG;
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:179
set_false_path -through [get_nets pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2]

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:181
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -period 10.000 -name sys_clk_c [get_pins refclk_ibuf/O]
#TIMESPEC TS_CLK_250 = PERIOD "CLK_250" TS_SYSCLK * 2.5 HIGH 50 % PRIORITY 2;
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:183
# The PRIORITY keyword is unsupported and will be ignored in the translation. Desired prioritization should be ensured manually
create_generated_clock -name pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_125mhz -source [get_pins refclk_ibuf/O] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:184
create_generated_clock -name pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1 -source [get_pins refclk_ibuf/O] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT2]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:185
create_generated_clock -name pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2 -source [get_pins refclk_ibuf/O] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]



set_property LOC MMCME2_ADV_X0Y2 [get_cells pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i]

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:191
set_false_path -from [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLPHYLNKUPN]
set_false_path -through [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLPHYLNKUPN]
set_false_path -to [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLPHYLNKUPN]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:192
set_false_path -from [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLRECEIVEDHOTRST]
set_false_path -through [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLRECEIVEDHOTRST]
set_false_path -to [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/pcie_top_i/pcie_7x_i/pcie_block_i/PLRECEIVEDHOTRST]

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:194
set_false_path -from [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/RST]
set_false_path -through [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/RST]
set_false_path -to [get_pins pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/RST]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:195
set_false_path -through [get_nets pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/user_resetdone*]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:196
set_false_path -through [get_nets pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_sel]

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:202
# Predefined group specifications on TNM/TNM_NET are unsupported and will be ignored in the translation. The generated xdc should be revised manually
# Predefined group specifications on TNM/TNM_NET are unsupported and will be ignored in the translation. The generated xdc should be revised manually
# Predefined group specifications on TNM/TNM_NET are unsupported and will be ignored in the translation. The generated xdc should be revised manually
# Predefined group specifications on TNM/TNM_NET are unsupported and will be ignored in the translation. The generated xdc should be revised manually
# Translation of path delay constraints may result in different analysis between ucf and xdc. For example, a path delay from/to pads that ends/begins at synchronous elements does not analyze clock latency/uncertainty in ucf but does in xdc
set_multicycle_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[1].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 2
set_multicycle_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[2].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 2
set_multicycle_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[3].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 2
set_multicycle_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[0].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 2
set_multicycle_path -hold -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[1].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 1
set_multicycle_path -hold -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[2].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 1
set_multicycle_path -hold -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[3].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 1
set_multicycle_path -hold -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_lane[0].gtp_pipe_rate.gtp_pipe_rate_i/*}]] 1


# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:206
set_false_path -through [get_nets pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/qpll_reset.qpll_reset_i/*]

###############################################################################
# Physical Constraints
###############################################################################

#########################################################################################################################
# End PCIe Core Constraints
#########################################################################################################################

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:216
####set_false_path -through [get_nets userclk_200MHz_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:218
# The conversion of 'IOSTANDARD' constraint on 'net' object 'userclk_200MHz_n' has been applied to the port object 'userclk_200MHz_n'.
####set_property IOSTANDARD LVCMOS33 [get_ports userclk_200MHz_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:219
####set_false_path -through [get_nets userclk_200MHz_p]
####set_property DIFF_TERM TRUE [get_ports userclk_200MHz_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:221
# The conversion of 'IOSTANDARD' constraint on 'net' object 'userclk_200MHz_p' has been applied to the port object 'userclk_200MHz_p'.
####set_property IOSTANDARD LVCMOS33 [get_ports userclk_200MHz_p]
####set_property DIFF_TERM TRUE [get_ports userclk_200MHz_p]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:222
####create_clock -period 5.000 -name userclk_200MHz_p [get_ports userclk_200MHz_p]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:223
####set_false_path -through [get_nets userclk_200MHz_p]


# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:227
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_clk_in_p' has been applied to the port object 'adc_clk_in_p'.
set_property IOSTANDARD LVDS_25 [get_ports adc_clk_in_p]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:228
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_clk_in_p' has been applied to the port object 'adc_clk_in_p'.
set_property DIFF_TERM TRUE [get_ports adc_clk_in_p]
set_property PACKAGE_PIN D19 [get_ports adc_clk_in_p]
set_property PACKAGE_PIN C19 [get_ports adc_clk_in_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:230
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_clk_in_n' has been applied to the port object 'adc_clk_in_n'.
set_property IOSTANDARD LVDS_25 [get_ports adc_clk_in_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:231
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_clk_in_n' has been applied to the port object 'adc_clk_in_n'.
set_property DIFF_TERM TRUE [get_ports adc_clk_in_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:233
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_or_p' has been applied to the port object 'adc_data_or_p'.
set_property IOSTANDARD LVDS_25 [get_ports adc_data_or_p]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:234
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_or_p' has been applied to the port object 'adc_data_or_p'.
set_property DIFF_TERM TRUE [get_ports adc_data_or_p]
set_property PACKAGE_PIN C17 [get_ports adc_data_or_p]
set_property PACKAGE_PIN B17 [get_ports adc_data_or_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:236
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_or_n' has been applied to the port object 'adc_data_or_n'.
set_property IOSTANDARD LVDS_25 [get_ports adc_data_or_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:237
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_or_n' has been applied to the port object 'adc_data_or_n'.
set_property DIFF_TERM TRUE [get_ports adc_data_or_n]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:239
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[0]' has been applied to the port object 'adc_data_in_p[0]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[0]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:240
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[0]' has been applied to the port object 'adc_data_in_p[0]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[0]}]
set_property LOC ILOGIC_X0Y226 [get_cells {ad9467_1/g_adc_if[0].i_data_ddr}]
set_property LOC IDELAY_X0Y226 [get_cells {ad9467_1/g_adc_if[0].i_data_idelay}]
set_property PACKAGE_PIN D18 [get_ports {adc_data_in_p[0]}]
set_property PACKAGE_PIN C18 [get_ports {adc_data_in_n[0]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:242
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[0]' has been applied to the port object 'adc_data_in_n[0]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[0]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:243
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[0]' has been applied to the port object 'adc_data_in_n[0]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[0]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:245
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[1]' has been applied to the port object 'adc_data_in_p[1]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[1]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:246
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[1]' has been applied to the port object 'adc_data_in_p[1]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[1]}]
set_property LOC ILOGIC_X0Y228 [get_cells {ad9467_1/g_adc_if[1].i_data_ddr}]
set_property LOC IDELAY_X0Y228 [get_cells {ad9467_1/g_adc_if[1].i_data_idelay}]
set_property PACKAGE_PIN E17 [get_ports {adc_data_in_p[1]}]
set_property PACKAGE_PIN E18 [get_ports {adc_data_in_n[1]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:248
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[1]' has been applied to the port object 'adc_data_in_n[1]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[1]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:249
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[1]' has been applied to the port object 'adc_data_in_n[1]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[1]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:251
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[2]' has been applied to the port object 'adc_data_in_p[2]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[2]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:252
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[2]' has been applied to the port object 'adc_data_in_p[2]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[2]}]
set_property LOC ILOGIC_X0Y248 [get_cells {ad9467_1/g_adc_if[2].i_data_ddr}]
set_property LOC IDELAY_X0Y248 [get_cells {ad9467_1/g_adc_if[2].i_data_idelay}]
set_property PACKAGE_PIN H14 [get_ports {adc_data_in_p[2]}]
set_property PACKAGE_PIN H15 [get_ports {adc_data_in_n[2]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:254
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[2]' has been applied to the port object 'adc_data_in_n[2]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[2]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:255
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[2]' has been applied to the port object 'adc_data_in_n[2]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[2]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:257
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[3]' has been applied to the port object 'adc_data_in_p[3]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[3]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:258
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[3]' has been applied to the port object 'adc_data_in_p[3]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[3]}]
set_property LOC IDELAY_X0Y246 [get_cells {ad9467_1/g_adc_if[3].i_data_idelay}]
set_property LOC ILOGIC_X0Y246 [get_cells {ad9467_1/g_adc_if[3].i_data_ddr}]
set_property PACKAGE_PIN G17 [get_ports {adc_data_in_p[3]}]
set_property PACKAGE_PIN F17 [get_ports {adc_data_in_n[3]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:260
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[3]' has been applied to the port object 'adc_data_in_n[3]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[3]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:261
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[3]' has been applied to the port object 'adc_data_in_n[3]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[3]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:263
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[4]' has been applied to the port object 'adc_data_in_p[4]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[4]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:264
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[4]' has been applied to the port object 'adc_data_in_p[4]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[4]}]
set_property LOC IDELAY_X0Y244 [get_cells {ad9467_1/g_adc_if[4].i_data_idelay}]
set_property LOC ILOGIC_X0Y244 [get_cells {ad9467_1/g_adc_if[4].i_data_ddr}]
set_property PACKAGE_PIN F18 [get_ports {adc_data_in_p[4]}]
set_property PACKAGE_PIN F19 [get_ports {adc_data_in_n[4]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:266
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[4]' has been applied to the port object 'adc_data_in_n[4]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[4]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:267
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[4]' has been applied to the port object 'adc_data_in_n[4]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[4]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:269
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[5]' has been applied to the port object 'adc_data_in_p[5]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[5]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:270
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[5]' has been applied to the port object 'adc_data_in_p[5]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[5]}]
set_property LOC IDELAY_X0Y242 [get_cells {ad9467_1/g_adc_if[5].i_data_idelay}]
set_property LOC ILOGIC_X0Y242 [get_cells {ad9467_1/g_adc_if[5].i_data_ddr}]
set_property PACKAGE_PIN G15 [get_ports {adc_data_in_p[5]}]
set_property PACKAGE_PIN F15 [get_ports {adc_data_in_n[5]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:272
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[5]' has been applied to the port object 'adc_data_in_n[5]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[5]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:273
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[5]' has been applied to the port object 'adc_data_in_n[5]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[5]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:275
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[6]' has been applied to the port object 'adc_data_in_p[6]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[6]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:276
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[6]' has been applied to the port object 'adc_data_in_p[6]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[6]}]
set_property LOC IDELAY_X0Y240 [get_cells {ad9467_1/g_adc_if[6].i_data_idelay}]
set_property LOC ILOGIC_X0Y240 [get_cells {ad9467_1/g_adc_if[6].i_data_ddr}]
set_property PACKAGE_PIN G19 [get_ports {adc_data_in_p[6]}]
set_property PACKAGE_PIN F20 [get_ports {adc_data_in_n[6]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:278
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[6]' has been applied to the port object 'adc_data_in_n[6]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[6]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:279
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[6]' has been applied to the port object 'adc_data_in_n[6]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[6]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:281
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_p[7]' has been applied to the port object 'adc_data_in_p[7]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_p[7]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:282
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_p[7]' has been applied to the port object 'adc_data_in_p[7]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_p[7]}]
set_property LOC IDELAY_X0Y238 [get_cells {ad9467_1/g_adc_if[7].i_data_idelay}]
set_property LOC ILOGIC_X0Y238 [get_cells {ad9467_1/g_adc_if[7].i_data_ddr}]
set_property PACKAGE_PIN H16 [get_ports {adc_data_in_p[7]}]
set_property PACKAGE_PIN G16 [get_ports {adc_data_in_n[7]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:284
# The conversion of 'IOSTANDARD' constraint on 'net' object 'adc_data_in_n[7]' has been applied to the port object 'adc_data_in_n[7]'.
set_property IOSTANDARD LVDS_25 [get_ports {adc_data_in_n[7]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:285
# The conversion of 'DIFF_TERM' constraint on 'net' object 'adc_data_in_n[7]' has been applied to the port object 'adc_data_in_n[7]'.
set_property DIFF_TERM TRUE [get_ports {adc_data_in_n[7]}]


#NET real_strobe_signal LOC = "V34" | IOSTANDARD = "LVCMOS25";   
#NET real_soa_signal LOC = "W34" | IOSTANDARD = "LVCMOS25";  

# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:292
create_clock -period 8.000 -name adc_clk_in_p [get_ports adc_clk_in_p]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:294
create_clock -period 8.000 -name adc_clk_in_n [get_ports adc_clk_in_n]

# The following cross clock domain false path constraints can be uncommented in order to mimic ucf constraints behavior (see message at the beginning of this file)
# set_false_path -from [get_clocks sys_clk_c] -to [get_clocks [list userclk_200MHz_p adc_clk_in_p adc_clk_in_n]]
# set_false_path -from [get_clocks pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_125mhz] -to [get_clocks [list userclk_200MHz_p adc_clk_in_p adc_clk_in_n]]
# set_false_path -from [get_clocks pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1] -to [get_clocks [list userclk_200MHz_p adc_clk_in_p adc_clk_in_n]]
# set_false_path -from [get_clocks pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2] -to [get_clocks [list userclk_200MHz_p adc_clk_in_p adc_clk_in_n]]
# set_false_path -from [get_clocks userclk_200MHz_p] -to [get_clocks [list sys_clk_c pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_125mhz pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1 pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2 adc_clk_in_p adc_clk_in_n]]
# set_false_path -from [get_clocks adc_clk_in_p] -to [get_clocks [list sys_clk_c pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_125mhz pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1 pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2 userclk_200MHz_p adc_clk_in_n]]
# set_false_path -from [get_clocks adc_clk_in_n] -to [get_clocks [list sys_clk_c pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/clk_125mhz pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1 pcie_axi_trn_bridge_i/v7_pcie_i/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk2 userclk_200MHz_p adc_clk_in_p]]



# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:297
# The conversion of 'IOSTANDARD' constraint on 'net' object 'delay_clk' has been applied to the port object 'delay_clk'.
# set_property IOSTANDARD LVCMOS18 [get_ports delay_clk]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:298
# The conversion of 'IOSTANDARD' constraint on 'net' object 'real_soa_signal' has been applied to the port object 'real_soa_signal'.
# set_property IOSTANDARD LVCMOS18 [get_ports real_soa_signal]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:299
# The conversion of 'IOSTANDARD' constraint on 'net' object 'real_strobe_signal' has been applied to the port object 'real_strobe_signal'.
# set_property IOSTANDARD LVCMOS18 [get_ports real_strobe_signal]
set_property IOSTANDARD LVCMOS18 [get_ports userclk_66MHz]
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[7]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:302
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[6]' has been applied to the port object 'LEDs_IO_pin[6]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[6]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[5]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:304
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[4]' has been applied to the port object 'LEDs_IO_pin[4]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[4]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:305
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[3]' has been applied to the port object 'LEDs_IO_pin[3]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[3]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:306
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[2]' has been applied to the port object 'LEDs_IO_pin[2]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[2]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:307
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[1]' has been applied to the port object 'LEDs_IO_pin[1]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[1]}]
# C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.runs/impl_1/.constrs/ABB3_pcie_4_lane_Emu_FIFO_elink.ucf:308
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LEDs_IO_pin[0]' has been applied to the port object 'LEDs_IO_pin[0]'.
# set_property IOSTANDARD LVCMOS18 [get_ports {LEDs_IO_pin[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs_IO_pin[0]}]
set_property PACKAGE_PIN D26 [get_ports {LEDs_IO_pin[7]}]
set_property PACKAGE_PIN H26 [get_ports {LEDs_IO_pin[6]}]
set_property PACKAGE_PIN G25 [get_ports {LEDs_IO_pin[4]}]
set_property PACKAGE_PIN G26 [get_ports {LEDs_IO_pin[5]}]
set_property PACKAGE_PIN F25 [get_ports {LEDs_IO_pin[3]}]
set_property PACKAGE_PIN J25 [get_ports {LEDs_IO_pin[2]}]
set_property PACKAGE_PIN J26 [get_ports {LEDs_IO_pin[1]}]
set_property PACKAGE_PIN L19 [get_ports {LEDs_IO_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports delay_clk]
set_property IOSTANDARD LVCMOS33 [get_ports real_soa_signal]
set_property IOSTANDARD LVCMOS33 [get_ports real_strobe_signal]
set_property PACKAGE_PIN G20 [get_ports delay_clk]
set_property PACKAGE_PIN E26 [get_ports real_soa_signal]
set_property PACKAGE_PIN D25 [get_ports real_strobe_signal]


make_diff_pair_ports adc_data_or_p adc_data_or_n


make_diff_pair_ports adc_data_or_p adc_data_or_n
make_diff_pair_ports adc_data_or_p adc_data_or_n
set_property PACKAGE_PIN P3 [get_ports userclk_200MHz_n]
set_property PACKAGE_PIN R3 [get_ports userclk_200MHz_p]
