# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/vsilantiev/VACAC701/VACAC701.data/wt [current_project]
set_property parent.project_dir D:/Users/vsilantiev/VACAC701 [current_project]
synth_design -top v7_eb_fifo_counted_resized -part xc7a200tfbg676-2 -mode out_of_context

rename_ref -prefix_all v7_eb_fifo_counted_resized
write_checkpoint -noxdef v7_eb_fifo_counted_resized.dcp
report_utilization -file v7_eb_fifo_counted_resized_utilization_synth.rpt -pb v7_eb_fifo_counted_resized_utilization_synth.pb
if { [catch {
  file copy -force D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_eb_fifo_counted_resized_synth_1/v7_eb_fifo_counted_resized.dcp d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized.dcp
  write_verilog -force -mode synth_stub d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized_stub.v
  write_verilog -force -mode funcsim d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized_funcsim.v
  write_vhdl -force -mode funcsim d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
