# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v7_sfifo_15x128 || ORIG_REF_NAME==v7_sfifo_15x128}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v7_mBuf_128x72 || ORIG_REF_NAME==v7_mBuf_128x72}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v7_eb_fifo_counted_resized || ORIG_REF_NAME==v7_eb_fifo_counted_resized}]]
