# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_sfifo_15x128_synth_1/v7_sfifo_15x128.dcp
set_property used_in_implementation false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_sfifo_15x128_synth_1/v7_sfifo_15x128.dcp]
set_property use_blackbox_stub false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_sfifo_15x128_synth_1/v7_sfifo_15x128.dcp]
add_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_mBuf_128x72_synth_1/v7_mBuf_128x72.dcp
set_property used_in_implementation false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_mBuf_128x72_synth_1/v7_mBuf_128x72.dcp]
set_property use_blackbox_stub false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_mBuf_128x72_synth_1/v7_mBuf_128x72.dcp]
add_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_eb_fifo_counted_resized_synth_1/v7_eb_fifo_counted_resized.dcp
set_property used_in_implementation false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_eb_fifo_counted_resized_synth_1/v7_eb_fifo_counted_resized.dcp]
set_property use_blackbox_stub false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.runs/v7_eb_fifo_counted_resized_synth_1/v7_eb_fifo_counted_resized.dcp]
read_verilog {
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/Emul.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_qpll_wrapper.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_rxeq_scan.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gtp_pipe_drp.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_rate.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gt_common.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_clock.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_user.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_sync.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_qpll_reset.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_reset.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_eq.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gtp_pipe_reset.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gt_wrapper.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_drp.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_qpll_drp.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pipe_wrapper.v
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gtp_pipe_rate.v
  d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_sfifo_15x128/v7_sfifo_15x128_stub.v
  d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72_stub.v
  d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_eb_fifo_counted_resized/v7_eb_fifo_counted_resized_stub.v
}
read_vhdl {
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/v6abb64Package_efifo_elink.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/FF_tagram64x36.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/DMA_FSM.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/DMA_Calculate.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/Tx_Output_Arbitor.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/tx_Mem_Reader.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_usDMA_Channel.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_MWr_Channel.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_MRd_Channel.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_dsDMA_Channel.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_CplD_Channel.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/RxIn_Delays.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/Interrupts.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/tx_Transact.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/rx_Transact.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/Registers.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/pcie_axi_trn_bridge.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/tlpControl.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/FIFO_Wrapper.vhd
  C:/Users/vsilantiev/Documents/VACAC701new/MySource/v6eb_pcie.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_tx_thrtl_ctl.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_pipe_pipeline.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_brams_7x.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gt_rx_valid_filter_7x.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_7x.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_bram_7x.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_top.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_rx_pipeline.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_gt_top.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_tx_pipeline.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_rx.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_bram_top_7x.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_pipe_misc.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_top.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_core_top.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_tx.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_pcie_pipe_lane.vhd
  D:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_pcie/v7_pcie/source/v7_pcie_axi_basic_rx_null_gen.vhd
}
read_xdc D:/Users/vsilantiev/VACAC701/VACAC701.srcs/constrs_1/new/ac701.xdc
set_property used_in_implementation false [get_files D:/Users/vsilantiev/VACAC701/VACAC701.srcs/constrs_1/new/ac701.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/vsilantiev/VACAC701/VACAC701.data/wt [current_project]
set_property parent.project_dir D:/Users/vsilantiev/VACAC701 [current_project]
synth_design -top v6pcieDMA -part xc7a200tfbg676-2
write_checkpoint v6pcieDMA.dcp
report_utilization -file v6pcieDMA_utilization_synth.rpt -pb v6pcieDMA_utilization_synth.pb
