# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72.xci
# IP: The module: 'v7_mBuf_128x72' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72/v7_mBuf_128x72.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_mBuf_128x72'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_mBuf_128x72'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72.xci
# IP: The module: 'v7_mBuf_128x72' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72/v7_mBuf_128x72.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_mBuf_128x72'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Users/vsilantiev/VACAC701/VACAC701.srcs/sources_1/ip/v7_mBuf_128x72/v7_mBuf_128x72_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_mBuf_128x72'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
